name = "telegram-bot-worker"
main = "src/index.js"
compatibility_date = "2024-04-06"

[vars]
ENV_BOT_TOKEN = "your_bot_token_here"
ENV_BOT_SECRET = "your_webhook_secret"
ENV_ADMIN_UID = "123456789"

[[kv_namespaces]]
binding = "nfd"
id = "your-kv-namespace-id"
